# Generated by Django 4.0.2 on 2022-03-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_pics', verbose_name='Image')),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
            ],
        ),
    ]
