# Generated by Django 4.0.3 on 2022-04-07 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0002_alter_like_post_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', through='instagram.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
